### ISSUE TITLE
config.yml issue

### ISSUE THREAD

**Issue by defconxt** [vpnwiz/kasm-working-with-traefik#1]
Hey! Thanks for this by the way...everything here worked great aside from me chasing an "Internal Service Error" down. It ended up being attributed to the config.yml entries...I tried several different modifications and could not get it working for hours and hours. I ended up wiping out the config, and then in the /opt/ docker-compose.yaml directory I substituted the following lines:

```
  proxy:
    container_name: kasm_proxy
    image: "kasmweb/nginx:latest"
    ports:
     - "8443:8443"
    expose:
     - "443"
    networks:
      - kasm_default_network
      - proxy
    volumes:
      - /docker/kasm/nginx.conf:/etc/nginx/nginx.conf # added from tutorial above to overwrite default nginx config.
      - /opt/kasm/1.13.0/conf/nginx:/etc/nginx/conf.d:ro
      - /opt/kasm/1.13.0/certs/kasm_nginx.key:/etc/ssl/private/kasm_nginx.key
      - /opt/kasm/1.13.0/certs/kasm_nginx.crt:/etc/ssl/certs/kasm_nginx.crt
      - /opt/kasm/1.13.0/www:/srv/www:ro
      - /opt/kasm/1.13.0/log/nginx:/var/log/external/nginx/
      - /opt/kasm/1.13.0/log/logrotate:/var/log/external/logrotate/
    depends_on:
      - kasm_manager
      - kasm_api
      - kasm_agent
      - kasm_share
      - kasm_guac
    labels:
     - traefik.enable=true
     - traefik.http.routers.kasm-https.rule=Host(`kasm.REDACTED-DOMAIN.com`)
     - traefik.http.routers.kasm-https.entrypoints=https
     - traefik.http.routers.kasm-https.service=kasm
     - traefik.http.services.kasm.loadbalancer.server.scheme=https
     - traefik.http.services.kasm.loadbalancer.server.port=8443
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
volumes:
  kasm_db_1.13.0:
    external: true
networks:
  kasm_default_network:
    external: true
  proxy:
    external: true
```

I'm fairly new to all of this, so it's probably on my part...but this worked for me above! Woohoo. Obviously replace "REDACTED-DOMAIN" with your own stuff.
